### ISSUE TITLE
【组件】[百川] worker 启动时报异常

### ISSUE THREAD

**Issue by meetbill** [meetbill/butterfly#12]
```
14:55:46 Worker rq:worker:37735a5963d04757b5e86b4ea63077d7: started, version 1.3.0
14:55:46 *** Listening on high, default, low...
14:55:46 Cleaning registries for queue: high
14:55:46 Cleaning registries for queue: default
14:55:46 Worker rq:worker:37735a5963d04757b5e86b4ea63077d7: found an unhandled exception, quitting...
Traceback (most recent call last):
  File "/tmp/rq-1.3.0/rq/worker.py", line 502, in work
    self.run_maintenance_tasks()
  File "/tmp/rq-1.3.0/rq/worker.py", line 462, in run_maintenance_tasks
    self.clean_registries()
  File "/tmp/rq-1.3.0/rq/worker.py", line 986, in clean_registries
    clean_registries(queue)
  File "/tmp/rq-1.3.0/rq/registry.py", line 309, in clean_registries
    registry.cleanup()
  File "/tmp/rq-1.3.0/rq/registry.py", line 136, in cleanup
    connection=self.connection)
  File "/tmp/rq-1.3.0/rq/job.py", line 303, in fetch
    job.refresh()
  File "/tmp/rq-1.3.0/rq/job.py", line 515, in refresh
    self.restore(data)
  File "/tmp/rq-1.3.0/rq/job.py", line 479, in restore
    self.ended_at = str_to_date(obj.get('ended_at'))
  File "/tmp/rq-1.3.0/rq/utils.py", line 256, in str_to_date
    return utcparse(as_text(date_str))
  File "/tmp/rq-1.3.0/rq/utils.py", line 172, in utcparse
    return datetime.datetime.strptime(string, '%Y-%m-%dT%H:%M:%SZ')
  File "/home/users/meetbill/.jumbo/lib/python2.7/_strptime.py", line 325, in _strptime
    (data_string, format))
ValueError: time data '' does not match format '%Y-%m-%dT%H:%M:%SZ'
```

**Comment by meetbill** [comment]
rq https://github.com/rq/rq/issues/1282
