### ISSUE TITLE
【组件】[如期] 添加任务时提示错误

### ISSUE THREAD

**Issue by meetbill** [meetbill/butterfly#13]
```
2020-09-28 20:14:16	25392	httpgateway.py:93	D08A2D87BF738808 Server exception
Traceback (most recent call last):
  File "/home/users/meetbill/butterfly_1.0.20/xlib/protocol_json.py", line 163, in __call__
    ret = self._func(**params)
  File "/home/users/meetbill/butterfly_1.0.20/handlers/ruqi/__init__.py", line 71, in add_job
    if crontab.add_job(name, rule, cmd):
  File "/home/users/meetbill/butterfly_1.0.20/handlers/ruqi/persistent.py", line 64, in add_job
    self.remove_job(name)
  File "/home/users/meetbill/butterfly_1.0.20/handlers/ruqi/persistent.py", line 120, in remove_job
    self.__remove_jobs(matchedJobs)
  File "/home/users/meetbill/butterfly_1.0.20/handlers/ruqi/persistent.py", line 127, in __remove_jobs
    self._scheduler.unschedule_job(job)
  File "/home/users/meetbill/butterfly_1.0.20/third/apscheduler/scheduler.py", line 432, in unschedule_job
    self._remove_job(job, alias, jobstore)
  File "/home/users/meetbill/butterfly_1.0.20/third/apscheduler/scheduler.py", line 294, in _remove_job
    jobstore.remove_job(job)
  File "/home/users/meetbill/butterfly_1.0.20/third/apscheduler/jobstores/shelve_store.py", line 52, in remove_job
    del self.store[job.id]
  File "/home/users/meetbill/.jumbo/lib/python2.7/shelve.py", line 136, in __delitem__
    del self.dict[key]
  File "/home/users/meetbill/.jumbo/lib/python2.7/bsddb/__init__.py", line 288, in __delitem__
    _DeadlockWrap(wrapF)  # del self.db[key]
  File "/home/users/meetbill/.jumbo/lib/python2.7/bsddb/dbutils.py", line 68, in DeadlockWrap
    return function(*_args, **_kwargs)
  File "/home/users/meetbill/.jumbo/lib/python2.7/bsddb/__init__.py", line 287, in wrapF
    del self.db[key]
DBRunRecoveryError: (-30978, 'DB_RUNRECOVERY: Fatal error, run database recovery -- PANIC: fatal region error detected; run recovery')
```

**Comment by meetbill** [comment]
> 当时的存储中的任务
```
{
    '696173': {
        'runs': 42,
        'name': u'tongji_excepthost',
        'misfire_grace_time': 1,
        'args': [],
        'next_run_time': datetime.datetime(2020, 9, 29, 14, 45),
        'max_instances': 1,
        'max_runs': None,
        'coalesce': True,
        'trigger': <CronTrigger (month='*', day='*', day_of_week='*', hour='14', minute='45', second='0')>,
        'func_ref': 'handlers.ruqi.persistent:run_cmd',
        'kwargs': {'cmd': u'python scripts/except_host.py count'},
        'id': '696173'
    },
    '931201': {
        'next_run_time': datetime.datetime(2020, 9, 28, 21, 3),
        'name': u'qn_host',
        'misfire_grace_time': 1,
        'args': [],
        'runs': 1617,
        'max_instances': 1,
        'max_runs': None,
        'coalesce': True,
        'trigger': <CronTrigger (month='*', day='*', day_of_week='*', hour='*', minute='3', second='0')>,
        'func_ref': 'handlers.ruqi.persistent:run_cmd',
        'kwargs': {'cmd': u'python scripts/qn_host/qn_host.py'},
        'id': '931201'
    },
    '463278': {
        'runs': 0,
        'name': u'qn_redis_336705',
        'misfire_grace_time': 1,
        'args': [],
        'next_run_time': datetime.datetime(2020, 9, 28, 20, 3, 10),
        'max_instances': 1,
        'max_runs': None,
        'coalesce': True,
        'trigger': <CronTrigger (month='*', day='*', day_of_week='*', hour='*', minute='*', second='*/10')>,
        'func_ref': 'handlers.ruqi.persistent:run_cmd',
        'kwargs': {'cmd': 'python scripts/cli.py action redis_336705'},
        'id': '463278'
    },
    '79869': {
        'runs': 14042,
        'name': u'decision',
        'misfire_grace_time': 1,
        'args': [],
        'next_run_time': datetime.datetime(2020, 9, 28, 20, 4),
        'max_instances': 1,
        'max_runs': None,
        'coalesce': True,
        'trigger': <CronTrigger (month='*', day='*', day_of_week='*', hour='*', minute='*', second='0')>,
        'func_ref': 'handlers.ruqi.persistent:run_cmd',
        'kwargs': {'cmd': u'python scripts/decision_cli.py action'},
        'id': '79869'
    },
    '644848': {
        'next_run_time': datetime.datetime(2020, 9, 28, 20, 3, 10),
        'name': u'qn_redis_357069',
        'misfire_grace_time': 1,
        'args': [],
        'runs': 3,
        'max_instances': 1,
        'max_runs': None,
        'coalesce': True,
        'trigger': <CronTrigger (month='*', day='*', day_of_week='*', hour='*', minute='*', second='*/10')>,
        'func_ref': 'handlers.ruqi.persistent:run_cmd',
        'kwargs': {'cmd': 'python scripts/cli.py action redis_357069'},
        'id': '644848'
    },
    '100038': {
        'next_run_time': datetime.datetime(2020, 9, 28, 21, 2),
        'name': u'tongji_matrix',
        'misfire_grace_time': 1,
        'args': [],
        'runs': 2397,
        'max_instances': 1,
        'max_runs': None,
        'coalesce': True,
        'trigger': <CronTrigger (month='*', day='*', day_of_week='*', hour='*', minute='2', second='0')>,
        'func_ref': 'handlers.ruqi.persistent:run_cmd',
        'kwargs': {'cmd': u'bash scripts/matrix/tongji_c_region.sh'},
        'id': '100038'
    }
}
```

**Comment by meetbill** [comment]
已去掉 shelve store 存储方式
