### ISSUE TITLE
【组件】[如期] Python 2.7 下 Mac 与 Centos 上使用 shelve jobstores 启动两个进程时有差异

### ISSUE THREAD

**Issue by meetbill** [meetbill/butterfly#19]
> 程序
```
import time

from xlib.apscheduler import scheduler
from xlib.apscheduler.jobstores.shelve_store import ShelveJobStore

_scheduler = scheduler.Scheduler()
_scheduler.add_jobstore(ShelveJobStore('example.db'), 'shelve')
_scheduler.start()

while True:
    time.sleep(2)
```

# 启动两个进程时
> mac，第二个进程会报如下异常（符合预期）
```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    _scheduler.add_jobstore(ShelveJobStore('example.db'), 'shelve')
  File "/Users/meetbill/butterfly/xlib/apscheduler/jobstores/shelve_store.py", line 24, in __init__
    self._open_store()
  File "/Users/meetbill/butterfly/xlib/apscheduler/jobstores/shelve_store.py", line 27, in _open_store
    self.store = shelve.open(self.path, 'c', self.pickle_protocol)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
gdbm.error: (35, 'Resource temporarily unavailable')
```
> Centos 下，第二个进程也可以正常启动
```
。。。
```

**Comment by meetbill** [comment]
已将 apscheduler 从 2.1.2 升级为 3.6.3 ，3.6.3 已去掉了 Shelve 模式
