### ISSUE TITLE
【启动】开启【百川】worker 功能时，当端口被占用时，提示服务启动成功，但此时服务不可用

### ISSUE THREAD

**Issue by meetbill** [meetbill/butterfly#29]
> 启动日志
```
Wed Feb 24 14:11:08 CST 2021
Traceback (most recent call last):
  File "/home/meetbill/butterfly_2/main.py", line 30, in <module>
    server.start()
  File "/home/meetbill/butterfly_2/xlib/cherrypy_wsgiserver/__init__.py", line 2068, in start
    raise socket.error(msg)
socket.error: No socket could be created -- (('0.0.0.0', 8005): [Errno 98] Address already in use)
```

**Comment by meetbill** [comment]
> 伪代码
```
import time
import threading

def ceshi():
    time.sleep(20)


t1=threading.Thread(target=ceshi)
t1.start()

raise "xxx"
```

**Comment by meetbill** [comment]
> 改造
```
t1=threading.Thread(target=ceshi)
t1.daemon = True   # MainThread 结束，子线程也立马结束
t1.start()
```

**Comment by meetbill** [comment]
或者 
```
t1.setDaemon(True)
```
