### ISSUE TITLE
【日志】定期 lograte 日志时线程不安全

### ISSUE THREAD

**Issue by meetbill** [meetbill/butterfly#33]
# 日志
```
2021-05-15 09:55:44	27125	/home/work/butterfly/xlib/httpgateway.py:261	D86AAFBCD0A36781 10.146.236.15 /wuxing/instance_get Make Acclog Error Traceback (most recent call last):
  File "/home/work/butterfly/xlib/httpgateway.py", line 256, in _mk_ret
    res=";".join(req.log_res))))
  File "/home/work/butterfly/xlib/logger/__init__.py", line 114, in log
    self._checkfile(now)
  File "/home/work/butterfly/xlib/logger/__init__.py", line 94, in _checkfile
    if os.fstat(self._fd).st_size > self._size_limit:
OSError: [Errno 9] Bad file descriptor
```

**Comment by meetbill** [comment]
# 分析
```
              |               |         |
--------V--------V-----V---------------------> 线程 A
             t1             t3        t4
-----------V-------------V-------------------> 线程 B
                   t2                    t5

t1 线程 A 发现日志打印行超过 FILE_SIZE_CHECK_LINES
t2 线程 B 发现日志打印行超过 FILE_SIZE_CHECK_LINES
t3 线程 A 检查日志文件是否大于设置的文件大小
t4 线程 A 进行关闭当前文件
t5 线程 B 检查日志文件是否大于设置的文件大小时异常
```

**Comment by meetbill** [comment]
在 https://github.com/meetbill/butterfly/commit/b4ac5da3d600faeb6852bdcc6290f4665b94203a 进行修复

修复策略
```
检查日志文件是否大于设置的文件大小时进行加锁
```
