### ISSUE TITLE
【组件】[百川] 消费限流时报错

### ISSUE THREAD

**Issue by meetbill** [meetbill/butterfly#37]
# 日志
```
ERROR xlib.mq.worker 07-13 14:55:57: /home/work/butterfly/xlib/mq/worker.py:625 140131455301376 @@@@@@@@@@@@@@@@ * worker get msg exception Traceback (most recent call last):
  File "/home/work/butterfly/xlib/mq/worker.py", line 606, in work
    self.queues, connection=self.connection, msg_class=self.msg_class)
  File "/home/work/butterfly/xlib/mq/queue.py", line 434, in dequeue_any
    result = cls.lpop(queues, connection=connection)
  File "/home/work/butterfly/xlib/mq/queue.py", line 401, in lpop
    if queue.rate_limit.limit('worker'):
  File "/home/work/butterfly/xlib/db/redisorm/rate_limit.py", line 71, in limit
    oldest = float(counter[-1])
TypeError: float() argument must be a string or a number
```

**Comment by meetbill** [comment]
# 代码
```
...
    49	    def limit(self, key):
    50	        """
    51	        Function to log an event with the given key. If the ``key`` has not
    52	        exceeded their alotted events, then the function returns ``False`` to
    53	        indicate that no limit is being imposed.
    54
    55	        If the ``key`` has exceeded the number of events, then the function
    56	        returns ``True`` indicating rate-limiting should occur.
    57
    58	        :param str key: A key identifying the source of the event.
    59	        :returns: Boolean indicating whether the event should be rate-limited
    60	            or not.
    61	        """
    62	        if self._debug:
    63	            return False
    64
    65	        counter = self.database.List(self.name + ':' + key)
    66	        n = len(counter)
    67	        is_limited = False
    68	        if n < self._limit:
    69	            counter.prepend(str(time.time()))
    70	        else:
    71	            oldest = float(counter[-1])
    72	            if time.time() - oldest < self._per:
    73	                is_limited = True
    74	            else:
    75	                counter.prepend(str(time.time()))
    76	            del counter[:self._limit]
    77	        counter.pexpire(int(self._per * 2000))
    78	        return is_limited
...
```

**Comment by meetbill** [comment]
len --> llen

**Comment by meetbill** [comment]
```
rate_limit = baichuan_cache.rate_limit('mylimit', limit=2, per=120)
rate_limit.limit('user-1')

#--------------------------------------------------------------------

49	    def limit(self, key):
50	        """
51	        Function to log an event with the given key. If the ``key`` has not
52	        exceeded their alotted events, then the function returns ``False`` to
53	        indicate that no limit is being imposed.
54
55	        If the ``key`` has exceeded the number of events, then the function
56	        returns ``True`` indicating rate-limiting should occur.
57
58	        :param str key: A key identifying the source of the event.
59	        :returns: Boolean indicating whether the event should be rate-limited
60	            or not.
61	        """
62	        if self._debug:
63	            return False
64
65	        counter = self.database.List(self.name + ':' + key)
            # LLEN("LLEN" "mylimit:user-1")
66	        n = len(counter)
67	        is_limited = False
68	        if n < self._limit:
                # LPUSH("LPUSH" "mylimit:user-1" "1637322694.49")
69	            counter.prepend(str(time.time()))
70	        else:
                # LINDEX("LINDEX" "mylimit:user-1" "-1")
71	            oldest = float(counter[-1])
72	            if time.time() - oldest < self._per:
73	                is_limited = True
74	            else:
                    # LPUSH("LPUSH" "mylimit:user-1" "1637322694.49")
75	                counter.prepend(str(time.time()))
                # LTRIM("LTRIM" "mylimit:user-1" "0" "1")
76	            del counter[:self._limit]
            # PEXPIRE("PEXPIRE" "mylimit:user-1" "240000")
77	        counter.pexpire(int(self._per * 2000))
78	        return is_limited
```

**Comment by meetbill** [comment]
> 每秒 30 次限速
```
queue.py
    name=queue_name
    self.rate_limit = self.connection.rate_limit(name, limit=30, per=1)
    ...
    queue.rate_limit.limit('worker')

假如调用 limit 的次数比较少，但多个消费者进行消费



                        t0                             t1                               t2                          t3
                        +-------------------------------+-------------------------------+---------------------------+-->
Thread 0  ("PEXPIRE" "mylimit:user-1" "2")
Thread 1                                    ("LLEN" "mylimit:user-1")               (key exipre)     ("LINDEX" "mylimit:user-1" "-1")


t0 时刻将限流的 list key 进行设置新的过期时间
t1 时刻其他线程拿到后，判断长度之后, 取最后一个元素时，此时 key 恰好已过期时就会有异常
```
