### ISSUE TITLE
【组件】[百川] 发布消息时超时

### ISSUE THREAD

**Issue by meetbill** [meetbill/butterfly#38]
> 日志
```
2021-07-15 19:20:55	13063	/home/butterfly/xlib/httpgateway.py:95	1829e1f8-40d3-43fd-9e4a-6640ad982eae Server exception
Traceback (most recent call last):
  File "/home/butterfly/xlib/protocol_json.py", line 173, in __call__
    ret = self._func(**params)
  File "/home/butterfly/handlers/xingqiao/__init__.py", line 139, in job_action
    msg_obj = mq_queue.enqueue(params_json, result_ttl=900)
  File "/home/butterfly/xlib/mq/queue.py", line 335, in enqueue
    at_front=result_data["at_front"], meta=result_data["meta"]
  File "/home/butterfly/xlib/mq/queue.py", line 291, in enqueue_call
    msg = self.enqueue_msg(msg, at_front=at_front)
  File "/home/butterfly/xlib/mq/queue.py", line 343, in enqueue_msg
    self.connection.sadd(self.redis_queues_keys, self.key)
  File "/home/butterfly/xlib/db/redis/client.py", line 2377, in sadd
    return self.execute_command('SADD', name, *values)
--------------------------------------------------------------------------------------+
  File "/home/butterfly/xlib/db/redis/client.py", line 1035, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/home/butterfly/xlib/db/redis/client.py", line 1043, in parse_response
    response = connection.read_response()
  File "/home/butterfly/xlib/db/redis/connection.py", line 817, in read_response
    response = self._parser.read_response()
  File "/home/butterfly/xlib/db/redis/connection.py", line 370, in read_response
    raw = self._buffer.readline()
  File "/home/butterfly/xlib/db/redis/connection.py", line 284, in readline
    self._read_from_socket()
  File "/home/butterfly/xlib/db/redis/connection.py", line 231, in _read_from_socket
    raise TimeoutError("Timeout reading from socket")
TimeoutError: Timeout reading from socket
```

**Comment by meetbill** [comment]
> butterfly/xlib/db/redis/client.py
```
1021-    # COMMAND EXECUTION AND PROTOCOL PARSING
1022:    def execute_command(self, *args, **options):
1023-        "Execute a command and return a parsed response"
1024-        pool = self.connection_pool
1025-        command_name = args[0]
1026-        conn = self.connection or pool.get_connection(command_name, **options)
1027-        try:
1028-            conn.send_command(*args)
1029-            return self.parse_response(conn, command_name, **options)
1030-        except (ConnectionError, TimeoutError) as e:
1031-            conn.disconnect()
1032-            if not (conn.retry_on_timeout and isinstance(e, TimeoutError)):
1033-                raise
1034-            conn.send_command(*args)
1035-            return self.parse_response(conn, command_name, **options)
1036-        finally:
1037-            if not self.connection:
1038-                pool.release(conn)
```

**Comment by meetbill** [comment]
当生产者在发布消息时，可能发生以下异常情况：

> * 消息没发出去：网络故障或其它问题导致发布失败，中间件直接返回失败
>    * 消息根本没发出去，那么重新发一次就好了。
> * 不确定是否发布成功：网络问题导致发布超时，可能数据已发送成功，但读取响应结果超时了
>    * 生产者没办法知道消息到底有没有发成功？所以，为了避免消息丢失，它也只能继续重试，直到发布成功为止。

**Comment by meetbill** [comment]
# 星桥 job_action 改为幂等方法
> 旧
```
job_action(job_id)
```
> 新
```
job_action(job_id, exe_id)
------------------------------
根据 exe_id 判断 job_action 是否执行
```
